# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: apssamp.tex
          working_directory: paper
          post_compile: "latexmk -c && mv apssamp.pdf .."
      - name: Push PDF file
        run: |
          git config --global user.name 'Ising-B'
          git config --global user.email '35210313+Yariazen@useres.noreply.github.com'
          git add apssamp.pdf
          git clean -f
          git commit -am "Automated commit"
          git push
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: paper/apssamp.pdf
          
